# Generated by Django 3.0.8 on 2020-07-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded_file',
            name='title',
            field=models.CharField(default='sampletitle', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploaded_file',
            name='content',
            field=models.FileField(upload_to=''),
        ),
    ]
